// scripts/submit-to-indexnow.ts
import { submitMultipleUrls } from '../lib/indexnow';

// All your sitemap URLs
const SITEMAP_URLS = [
  'https://mountainspineorthopedics.com/',
  'https://mountainspineorthopedics.com/about',
  'https://mountainspineorthopedics.com/condition-check',
  'https://mountainspineorthopedics.com/privacy-policy',
  'https://mountainspineorthopedics.com/area-of-specialty',
  'https://mountainspineorthopedics.com/locations',
  'https://mountainspineorthopedics.com/locations/hollywood-fl-orthopedics',
  'https://mountainspineorthopedics.com/locations/palm-springs-orthopedics',
  'https://mountainspineorthopedics.com/locations/orlando-orthopedics',
  'https://mountainspineorthopedics.com/locations/fort-pierce-orthopedics',
  'https://mountainspineorthopedics.com/locations/palm-beach-gardens-orthopedics',
  'https://mountainspineorthopedics.com/locations/miami-beach-orthopedics',
  'https://mountainspineorthopedics.com/locations/boca-raton-orthopedics',
  'https://mountainspineorthopedics.com/locations/altamonte-springs-orthopedics',
  'https://mountainspineorthopedics.com/locations/davenport-orthopedics',
  'https://mountainspineorthopedics.com/find-care/book-an-appointment',
  'https://mountainspineorthopedics.com/find-care/find-a-doctor',
  'https://mountainspineorthopedics.com/find-care/free-mri-review',
  'https://mountainspineorthopedics.com/find-care/candidacy-check',
  'https://mountainspineorthopedics.com/insurance-policy',
  'https://mountainspineorthopedics.com/patient-forms',
  'https://mountainspineorthopedics.com/find-care/second-opinion',
  'https://mountainspineorthopedics.com/area-of-pain/back-pain/lower-back-pain',
  'https://mountainspineorthopedics.com/area-of-pain/back-pain/lumbar-degenerative-disc-disease',
  'https://mountainspineorthopedics.com/area-of-pain/back-pain/lumbar-herniated-disc',
  'https://mountainspineorthopedics.com/area-of-pain/back-pain/foraminal-stenosis-back-pain',
  'https://mountainspineorthopedics.com/area-of-pain/back-pain/sciatica-nerve-pain',
  'https://mountainspineorthopedics.com/area-of-pain/back-pain/tailbone-pain-coccydynia',
  'https://mountainspineorthopedics.com/area-of-pain/back-pain/back-pain-treatment-options',
  'https://mountainspineorthopedics.com/area-of-pain/neck-and-shoulder-pain/neck-spinal-stenosis',
  'https://mountainspineorthopedics.com/area-of-pain/neck-and-shoulder-pain/neck-herniated-disc',
  'https://mountainspineorthopedics.com/area-of-pain/neck-and-shoulder-pain/cervical-degenerative-disc-disease',
  'https://mountainspineorthopedics.com/area-of-pain/neck-and-shoulder-pain/neck-shoulder-arthritis-pain',
  'https://mountainspineorthopedics.com/area-of-pain/neck-and-shoulder-pain/pinched-nerve-neck-shoulder',
  'https://mountainspineorthopedics.com/area-of-pain/neck-and-shoulder-pain/neck-and-shoulder-pain-treatment',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/bunion-pain-hallux-valgus',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/heel-pain-plantar-fasciitis',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/flat-feet-pain',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/ankle-arthroscopy-recovery-pain',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/hammertoes-foot-pain',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/diabetic-foot-ulcer-care',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/ankle-replacement-surgery-pain',
  'https://mountainspineorthopedics.com/area-of-pain/foot-pain/achilles-tendon-pain',
  'https://mountainspineorthopedics.com/injuries/car-accident',
  'https://mountainspineorthopedics.com/injuries/slip-and-fall',
  'https://mountainspineorthopedics.com/about/meetourdoctors/dr-scott-katzman',
  'https://mountainspineorthopedics.com/about/meetourdoctors/dr-david-cowin',
  'https://mountainspineorthopedics.com/about/meetourdoctors/dr-christopher-mccarthy',
  'https://mountainspineorthopedics.com/about/meetourdoctors/dr-monica-mcphail-pruitt',
  'https://mountainspineorthopedics.com/about/meetourdoctors/dr-douglas-slaughter',
  'https://mountainspineorthopedics.com/area-of-specialty/adult-degenerative-scoliosis',
  'https://mountainspineorthopedics.com/area-of-specialty/adjacent-segment-disease',
  'https://mountainspineorthopedics.com/area-of-specialty/lumbar-herniated-disc',
  'https://mountainspineorthopedics.com/area-of-specialty/degenerative-disc-disease',
  'https://mountainspineorthopedics.com/area-of-specialty/cervical-spinal-stenosis',
  'https://mountainspineorthopedics.com/area-of-specialty/spondylolisthesis',
  'https://mountainspineorthopedics.com/area-of-specialty/cervical-herniated-disc',
  'https://mountainspineorthopedics.com/area-of-specialty/spinal-compression-fractures',
  'https://mountainspineorthopedics.com/area-of-specialty/kyphosis',
  'https://mountainspineorthopedics.com/area-of-specialty/osteoarthritis',
  'https://mountainspineorthopedics.com/area-of-specialty/rotator-cuff-tear',
  'https://mountainspineorthopedics.com/area-of-specialty/acl-injury',
  'https://mountainspineorthopedics.com/area-of-specialty/labral-tears',
  'https://mountainspineorthopedics.com/area-of-specialty/torn-meniscus',
  'https://mountainspineorthopedics.com/area-of-specialty/sacroiliac-joint-dysfunction',
  'https://mountainspineorthopedics.com/area-of-specialty/trochanteric-bursitis',
  'https://mountainspineorthopedics.com/area-of-specialty/carpal-tunnel-syndrome',
  'https://mountainspineorthopedics.com/area-of-specialty/back-pain',
  'https://mountainspineorthopedics.com/area-of-specialty/bulging-disc',
  'https://mountainspineorthopedics.com/area-of-specialty/pinched-nerve',
  'https://mountainspineorthopedics.com/area-of-specialty/cervical-deformities',
  'https://mountainspineorthopedics.com/area-of-specialty/disc-tear',
  'https://mountainspineorthopedics.com/area-of-specialty/hip-dysplasia',
  'https://mountainspineorthopedics.com/area-of-specialty/facet-joint-disease',
  'https://mountainspineorthopedics.com/area-of-specialty/arthritis',
  'https://mountainspineorthopedics.com/area-of-specialty/lower-back-pain',
  'https://mountainspineorthopedics.com/area-of-specialty/sciatica',
  'https://mountainspineorthopedics.com/area-of-specialty/coccydynia',
  'https://mountainspineorthopedics.com/area-of-specialty/failed-back-surgery-syndrome',
  'https://mountainspineorthopedics.com/area-of-specialty/foraminal-stenosis',
  'https://mountainspineorthopedics.com/area-of-specialty/hip-impingement',
  'https://mountainspineorthopedics.com/area-of-specialty/loose-bodies',
  'https://mountainspineorthopedics.com/area-of-specialty/aging-management',
  'https://mountainspineorthopedics.com/area-of-specialty/neck-pain',
  'https://mountainspineorthopedics.com/area-of-specialty/degenerative-disc-disease-surgery',
  'https://mountainspineorthopedics.com/area-of-specialty/pseudarthrosis-revision-surgery',
  'https://mountainspineorthopedics.com/area-of-specialty/shoulder-arthritis',
  'https://mountainspineorthopedics.com/area-of-specialty/shoulder-tendonitis',
  'https://mountainspineorthopedics.com/area-of-specialty/snapping-hip-syndrome',
  'https://mountainspineorthopedics.com/area-of-specialty/spinal-bone-spurs',
  'https://mountainspineorthopedics.com/area-of-specialty/spinal-stenosis',
  'https://mountainspineorthopedics.com/area-of-specialty/spine-deformities',
  'https://mountainspineorthopedics.com/area-of-specialty/synovitis',
  'https://mountainspineorthopedics.com/area-of-specialty/tingling-or-numbness-in-extremities',
  'https://mountainspineorthopedics.com/area-of-specialty/herniated-disc',
  'https://mountainspineorthopedics.com/area-of-specialty/rheumatoid-arthritis',
  'https://mountainspineorthopedics.com/area-of-specialty/tennis-elbow',
  'https://mountainspineorthopedics.com/area-of-specialty/plantar-fasciitis',
  'https://mountainspineorthopedics.com/area-of-specialty/bursitis',
  'https://mountainspineorthopedics.com/area-of-specialty/bunions-hallux-valgus',
  'https://mountainspineorthopedics.com/area-of-specialty/achilles-tendonitis',
  'https://mountainspineorthopedics.com/area-of-specialty/flat-feet',
  'https://mountainspineorthopedics.com/area-of-specialty/ankle-arthroscopy',
  'https://mountainspineorthopedics.com/area-of-specialty/hammer-toes',
  'https://mountainspineorthopedics.com/area-of-specialty/diabetic-foot-ulcers',
  'https://mountainspineorthopedics.com/area-of-specialty/ankle-replacement',
  'https://mountainspineorthopedics.com/treatments/revision-spinal-surgery',
  'https://mountainspineorthopedics.com/treatments/multilevel-degenerative-disc-disease-surgery',
  'https://mountainspineorthopedics.com/treatments/anterior-lumbar-corpectomy-and-fusion',
  'https://mountainspineorthopedics.com/treatments/anterior-lumbar-interbody-fusion',
  'https://mountainspineorthopedics.com/treatments/hybrid-lumbar-spine-surgery',
  'https://mountainspineorthopedics.com/treatments/lumbar-fusion-surgery',
  'https://mountainspineorthopedics.com/treatments/spinal-fusion',
  'https://mountainspineorthopedics.com/treatments/understanding-tlif-surgery',
  'https://mountainspineorthopedics.com/treatments/posterior-cervical-fusion-with-instrumentation-surgery',
  'https://mountainspineorthopedics.com/treatments/posterior-cervical-fusion-surgery',
  'https://mountainspineorthopedics.com/treatments/anterior-cervical-corpectomy-and-fusion',
  'https://mountainspineorthopedics.com/treatments/acdf-surgery',
  'https://mountainspineorthopedics.com/treatments/lumbar-disc-replacement-surgery',
  'https://mountainspineorthopedics.com/treatments/artificial-disc-replacement-surgery',
  'https://mountainspineorthopedics.com/treatments/cervical-disc-arthroplasty',
  'https://mountainspineorthopedics.com/treatments/motion-preservation-spine-surgery',
  'https://mountainspineorthopedics.com/treatments/total-hip-replacement',
  'https://mountainspineorthopedics.com/treatments/total-knee-replacement',
  'https://mountainspineorthopedics.com/treatments/posterior-cervical-laminoplasty',
  'https://mountainspineorthopedics.com/treatments/posterior-cervical-foraminotomy-surgery',
  'https://mountainspineorthopedics.com/treatments/lumbar-laminectomy-surgery',
  'https://mountainspineorthopedics.com/treatments/lumbar-decompression',
  'https://mountainspineorthopedics.com/treatments/lumbar-microendoscopic-discectomy-surgery',
  'https://mountainspineorthopedics.com/treatments/lumbar-microdiscectomy-surgery',
  'https://mountainspineorthopedics.com/treatments/degenerative-disc-disease-surgery',
  'https://mountainspineorthopedics.com/treatments/percutaneous-discectomy',
  'https://mountainspineorthopedics.com/treatments/resurfacing-shoulder-replacement',
  'https://mountainspineorthopedics.com/treatments/hip-arthroscopy-treatment',
  'https://mountainspineorthopedics.com/treatments/arthroscopic-knee-surgery',
  'https://mountainspineorthopedics.com/treatments/rotator-cuff-repair-surgery',
  'https://mountainspineorthopedics.com/treatments/meniscus-repair-surgery',
  'https://mountainspineorthopedics.com/treatments/disc-replacement-vs-fusion-what-you-need-to-know',
  'https://mountainspineorthopedics.com/treatments/ankle-ligament-reconstruction-surgery',
  'https://mountainspineorthopedics.com/treatments/axial-fusion-surgery',
  'https://mountainspineorthopedics.com/treatments/hybrid-cervical-spine-surgery',
  'https://mountainspineorthopedics.com/treatments/back-pain-treatment',
  'https://mountainspineorthopedics.com/treatments/bunion-correction-surgery',
  'https://mountainspineorthopedics.com/treatments/carpal-tunnel-release',
  'https://mountainspineorthopedics.com/treatments/cervical-disc-replacement',
  'https://mountainspineorthopedics.com/treatments/coccygectomy-tailbone-removal-surgery',
  'https://mountainspineorthopedics.com/treatments/anti-inflammatory-injections-for-joint-and-spine-pain',
  'https://mountainspineorthopedics.com/treatments/aging-management',
  'https://mountainspineorthopedics.com/treatments/coccyx-nerve-ablation',
  'https://mountainspineorthopedics.com/treatments/cortisone-injections-for-back-pain',
  'https://mountainspineorthopedics.com/treatments/degenerative-disc-disease-surgery-details',
  'https://mountainspineorthopedics.com/treatments/endoscopic-discectomy-surgery',
  'https://mountainspineorthopedics.com/treatments/endoscopic-foraminotomy-surgery',
  'https://mountainspineorthopedics.com/treatments/acl-reconstruction-surgery',
  'https://mountainspineorthopedics.com/treatments/epidural-steroid-injection',
  'https://mountainspineorthopedics.com/treatments/extreme-lateral-interbody-fusion-surgery',
  'https://mountainspineorthopedics.com/treatments/facet-ablation-rhizotomy-treatment',
  'https://mountainspineorthopedics.com/treatments/facet-block-ablation-rhizotomy-and-facet-fusion-treatment-information',
  'https://mountainspineorthopedics.com/treatments/fracture-fixation',
  'https://mountainspineorthopedics.com/treatments/impar-block-treatment',
  'https://mountainspineorthopedics.com/treatments/neck-pain-treatment-and-shoulder-pain-relief',
  'https://mountainspineorthopedics.com/treatments/non-surgical-treatments-for-pain-management',
  'https://mountainspineorthopedics.com/treatments/oblique-lumbar-interbody-fusion',
  'https://mountainspineorthopedics.com/treatments/percutaneous-carpal-tunnel-release',
  'https://mountainspineorthopedics.com/treatments/shoulder-arthroscopy',
  'https://mountainspineorthopedics.com/treatments/stem-cell-treatment',
  'https://mountainspineorthopedics.com/treatments/surgical-treatments',
  'https://mountainspineorthopedics.com/treatments/trigger-finger-release',
  'https://mountainspineorthopedics.com/treatments/ankle-replacement-surgery',
  'https://mountainspineorthopedics.com/treatments/ankle-arthroscopy-minimally-invasive-surgery',
  'https://mountainspineorthopedics.com/blogs',
  'https://mountainspineorthopedics.com/blogs/boca-raton-back-pain-orthopedic-guide',
  'https://mountainspineorthopedics.com/blogs/orthopedic-doctor-for-sciatica-treatment',
  'https://mountainspineorthopedics.com/blogs/what-is-orthopedic-physical-therapy',
  'https://mountainspineorthopedics.com/blogs/orthopedic-impairment',
  'https://mountainspineorthopedics.com/blogs/what-is-the-hardest-orthopedic-surgery-to-recover-from',
  'https://mountainspineorthopedics.com/blogs/how-long-does-an-orthopedic-appointment-take',
  'https://mountainspineorthopedics.com/blogs/orthopedic-injury',
  'https://mountainspineorthopedics.com/blogs/getting-a-second-opinion-from-an-orthopedic-doctor',
  'https://mountainspineorthopedics.com/blogs/tag/back-pain',
  'https://mountainspineorthopedics.com/blogs/tag/neck-pain',
  'https://mountainspineorthopedics.com/blogs/tag/joint-care',
  'https://mountainspineorthopedics.com/blogs/tag/spinal-surgery',
  'https://mountainspineorthopedics.com/blogs/tag/sports-injury',
  'https://mountainspineorthopedics.com/blogs/tag/recovery',
  'https://mountainspineorthopedics.com/blogs/tag/minimally-invasive',
  'https://mountainspineorthopedics.com/blogs/tag/spine',
  'https://mountainspineorthopedics.com/blogs/tag/lower-spine',
  'https://mountainspineorthopedics.com/blogs/tag/neck',
  'https://mountainspineorthopedics.com/blogs/tag/shoulder',
  'https://mountainspineorthopedics.com/blogs/tag/knee',
  'https://mountainspineorthopedics.com/blogs/tag/hand',
  'https://mountainspineorthopedics.com/blogs/tag/foot',
];

async function submitAllUrls() {
  console.log(`🚀 Submitting ${SITEMAP_URLS.length} URLs to IndexNow...`);
  
  const results = await submitMultipleUrls(SITEMAP_URLS, 10);
  
  let successCount = 0;
  let errorCount = 0;
  
  results.forEach((result, index) => {
    if (result.success) {
      successCount++;
      console.log(`✅ Batch ${index + 1}: ${result.message}`);
    } else {
      errorCount++;
      console.error(`❌ Batch ${index + 1}: ${result.message}`);
    }
  });
  
  console.log(`\n📊 Summary:`);
  console.log(`✅ Successful batches: ${successCount}`);
  console.log(`❌ Failed batches: ${errorCount}`);
  console.log(`📄 Total URLs submitted: ${SITEMAP_URLS.length}`);
  
  if (successCount > 0) {
    console.log(`\n🎉 IndexNow submission completed! Check Bing Webmaster Tools to verify.`);
  }
}

// Run the script
submitAllUrls().catch(console.error);
